import { Database, FlaskConical, Radio } from "lucide-react";
import Link from "next/link";
import { timeAgo } from "@/lib/format";
import { SOURCE_LABELS, type DataSource } from "@/lib/providers/labels";
import { cn } from "@/lib/utils";
import { Tooltip } from "@/components/ui/tooltip";

/**
 * Provenance badge. Required on every report: demo data must never be mistaken for measurements.
 */
export function DataSourceBadge({ source, fetchedAt, note, className }: { source: DataSource; fetchedAt?: string; note?: string; className?: string }) {
  const isDemo = source === "demo";
  const text = isDemo
    ? "Deterministic sample data generated by SynapseSEO's demo engine — not measured from the web. Connect DataForSEO in Settings for live index data."
    : `Source: ${SOURCE_LABELS[source]}${fetchedAt ? ` · fetched ${timeAgo(fetchedAt)}` : ""}${note ? ` · ${note}` : ""}`;
  return (
    <Tooltip content={text} side="bottom" className={className}>
      <span
        className={cn(
          "inline-flex h-6 items-center gap-1.5 rounded-full border px-2.5 text-[11.5px] font-medium",
          isDemo ? "border-warning/50 bg-warning-soft text-warning-ink" : "border-good/40 bg-good-soft text-good-ink",
        )}
      >
        {isDemo ? <FlaskConical className="h-3.5 w-3.5" /> : source === "crawler" ? <Radio className="h-3.5 w-3.5" /> : <Database className="h-3.5 w-3.5" />}
        {SOURCE_LABELS[source]}
        {!isDemo && fetchedAt && <span className="font-normal opacity-80">· {timeAgo(fetchedAt)}</span>}
      </span>
    </Tooltip>
  );
}

export function DemoNotice({ className }: { className?: string }) {
  return (
    <p className={cn("text-[12px] text-text-3", className)}>
      Numbers marked <span className="font-medium text-warning-ink">Demo data</span> are synthetic. <Link href="/settings" className="text-link hover:underline">Connect a data provider</Link> for live metrics.
    </p>
  );
}
