import type { Category, Severity, ThemeKey } from "./types";

/** Client-safe catalog of every Site Audit check with its "Why and how to fix it" guidance. */
export type CheckDef = {
  id: string;
  title: string;
  severity: Severity;
  category: Category;
  /** "page": one row per affected URL; "link": one row per affected link (source URL + target); "site": site-wide. */
  scope: "page" | "link" | "site";
  why: string;
  how: string;
};

const c = (id: string, severity: Severity, category: Category, scope: CheckDef["scope"], title: string, why: string, how: string): CheckDef => ({ id, title, severity, category, scope, why, how });

export const THRESHOLDS = {
  titleMax: 70,
  titleMin: 30,
  descMax: 160,
  descMin: 70,
  wordsMin: 200,
  textRatioMin: 10,
  linksMax: 300,
  depthMax: 3,
  slowMs: 1000,
  verySlowMs: 3000,
  htmlLarge: 2_000_000,
  urlMax: 200,
  paramsMax: 2,
  resourcesMax: 30,
  certDays: 30,
};

export const CHECKS: CheckDef[] = [
  /* ------------------------------------------------ Errors ------------------------------------------------ */
  c("http-5xx", "error", "Crawlability", "page", "Pages returned 5XX status code",
    "A 5XX response means the server failed to deliver the page. Users see an error, and search engines that repeatedly get server errors crawl the site less and may drop the URLs from the index.",
    "Check the server and application logs for these URLs at the crawl time. Fix crashes, timeouts and overloaded upstreams; if the server is overloaded by crawling, raise capacity instead of blocking bots."),
  c("http-4xx", "error", "Crawlability", "page", "Pages returned 4XX status code",
    "A 4XX response means the page is missing or inaccessible. Internal links to it waste crawl budget and link equity, and visitors hit a dead end.",
    "Restore the page if it was removed by mistake, 301-redirect it to the most relevant live page, or remove/update every internal link pointing to it (see the “Found on” column)."),
  c("fetch-failed", "error", "Crawlability", "page", "Pages couldn't be crawled",
    "The crawler could not get any HTTP response (DNS failure, refused connection, TLS error or timeout). Search engines hitting the same problem cannot index these URLs.",
    "Open the URL yourself and check DNS, firewall/WAF rules and the TLS certificate. Make sure the server answers within a few seconds for every URL."),
  c("robots-unavailable", "error", "Crawlability", "site", "robots.txt can't be fetched",
    "When robots.txt returns a 5XX error or times out, Google treats the whole site as disallowed and stops crawling until it becomes available.",
    "Make /robots.txt return 200 with your rules (or 404 if you have none). Never let it return server errors or hang."),
  c("broken-internal-links", "error", "Internal linking", "link", "Broken internal links",
    "Links to internal pages that return 4XX/5XX send visitors and crawlers to dead ends and waste link equity.",
    "Update each link to point at a live URL, or restore/redirect the target page. The list shows each source page and the broken target."),
  c("broken-external-links", "error", "Internal linking", "link", "Broken external links",
    "Outgoing links that return 4XX/5XX (or whose domain no longer resolves) hurt user experience and signal a poorly maintained page.",
    "Replace each broken link with a working source or remove it. Sites that block bots (401/403/429) are not counted as broken."),
  c("broken-internal-images", "error", "Content", "link", "Broken internal images",
    "Images that return 4XX/5XX show as broken on the page and cannot appear in image search.",
    "Re-upload the missing files or update the <img src> to the correct path. Remove images that are no longer needed."),
  c("broken-resources", "error", "Performance", "link", "Broken internal JavaScript and CSS files",
    "Scripts and stylesheets that fail to load can break layout and functionality, and Google may render the page incorrectly.",
    "Fix the file paths or restore the files; check your build/deploy for missing assets and stale cache-busting names."),
  c("redirect-loop", "error", "Crawlability", "page", "Redirect loops and endless chains",
    "A redirect that eventually points back to itself (or needs more than 10 hops) never resolves: browsers show an error and crawlers give up.",
    "Trace the chain shown for each URL and make the first URL redirect straight to the final, live destination."),
  c("missing-title", "error", "Content", "page", "Missing or empty title tag",
    "The <title> is the main headline in search results and a strong relevance signal. Without it Google invents one, usually poorly.",
    "Add a unique, descriptive <title> (about 30–60 characters) to every indexable page."),
  c("duplicate-title", "error", "Content", "page", "Duplicate title tags",
    "Several indexable pages share the same title, so search engines struggle to tell which page is relevant for a query and may show the wrong one.",
    "Write a unique title for each page that reflects its specific content. If the pages really are duplicates, consolidate them or set a canonical."),
  c("duplicate-description", "error", "Content", "page", "Duplicate meta descriptions",
    "Identical descriptions make result snippets look the same and hide what makes each page different.",
    "Write a unique meta description for each page summarizing its specific content and value."),
  c("duplicate-content", "error", "Content", "page", "Duplicate content",
    "These pages have identical or nearly identical main text (at least 90% of their word sequences overlap). Search engines pick one version and may ignore the rest, splitting ranking signals.",
    "Merge the duplicates, make each page substantially unique, or point duplicates to the preferred URL with rel=canonical or a 301 redirect."),
  c("canonical-broken", "error", "Crawlability", "page", "Canonical URL points to a 4XX/5XX page",
    "The canonical tells search engines which URL to index. Pointing it at a broken page asks them to index an error.",
    "Point rel=canonical at the live, preferred version of the page (usually the page itself)."),
  c("multiple-canonicals", "error", "Crawlability", "page", "More than one canonical URL",
    "When a page declares several different canonical URLs (in HTML and/or the Link header), search engines ignore all of them.",
    "Keep exactly one rel=canonical per page and make HTML and HTTP header agree."),
  c("canonical-invalid", "error", "Crawlability", "page", "Malformed or empty canonical URL",
    "An empty, relative-to-nowhere or non-HTTP canonical value is ignored and suggests a template bug.",
    "Use an absolute https:// URL in rel=canonical."),
  c("invalid-structured-data", "error", "Markup", "page", "Invalid structured data (JSON-LD)",
    "JSON-LD that cannot be parsed, or lacks @context/@type, is ignored, so the page loses rich-result eligibility.",
    "Fix the JSON syntax (trailing commas, unescaped quotes) and include @context \"https://schema.org\" and a @type. Validate with the Rich Results Test."),
  c("hreflang-invalid-code", "error", "International SEO", "page", "Invalid hreflang language codes",
    "hreflang values must be ISO 639-1 language codes with an optional ISO 3166-1 region (e.g. en, en-GB) or x-default. Invalid codes are ignored.",
    "Correct each code (e.g. use en-GB, not en-UK or english)."),
  c("hreflang-no-return", "error", "International SEO", "link", "Missing hreflang return links",
    "hreflang annotations must be reciprocal: if page A lists page B as an alternate, B must list A. Otherwise search engines ignore the pair.",
    "Add the missing return annotation on each target page so every alternate lists every other alternate, including itself."),
  c("hreflang-broken", "error", "International SEO", "link", "hreflang links to broken or redirected pages",
    "Alternate URLs in hreflang must return 200 and be canonical. Broken or redirecting targets invalidate the annotation.",
    "Update hreflang to point at the final, live URL of each language version."),
  c("hreflang-conflict", "error", "International SEO", "page", "Conflicting hreflang values",
    "The same language code points to different URLs on one page, so search engines cannot decide which alternate to use.",
    "Keep one URL per hreflang value on each page."),
  c("https-not-supported", "error", "HTTPS", "site", "Website doesn't support HTTPS",
    "The site could not be reached over HTTPS. Browsers mark HTTP pages as “Not secure” and HTTPS is a ranking signal.",
    "Install a TLS certificate (e.g. Let's Encrypt), serve every page over HTTPS and redirect HTTP to HTTPS."),
  c("no-https-redirect", "error", "HTTPS", "site", "HTTP homepage doesn't redirect to HTTPS",
    "The HTTP version of the homepage serves content instead of redirecting, creating duplicate versions and exposing visitors to an insecure page.",
    "Add a site-wide 301 redirect from http:// to https:// at the server or CDN."),
  c("cert-invalid", "error", "HTTPS", "site", "Invalid security certificate",
    "Browsers block pages with an expired, self-signed or mismatched certificate behind a full-page warning.",
    "Renew/replace the certificate so it is issued by a trusted CA, covers every host name, and includes the full chain."),
  c("cert-expiring", "error", "HTTPS", "site", "Security certificate expires soon",
    "The certificate expires within 30 days. When it lapses, visitors see a blocking security warning.",
    "Renew the certificate now and enable automatic renewal."),
  c("old-tls", "error", "HTTPS", "site", "Old security protocol version",
    "TLS 1.0 and 1.1 are deprecated and blocked by modern browsers.",
    "Enable TLS 1.2 and 1.3 and disable older protocol versions in the server/CDN configuration."),
  c("www-both", "error", "Crawlability", "site", "www and non-www versions both serve content",
    "The site answers on both www and non-www host names without redirecting, creating duplicate copies of every page.",
    "Pick one host name and 301-redirect the other one to it (every path), then use it consistently in canonicals and sitemaps."),
  c("sitemap-invalid", "error", "Crawlability", "site", "sitemap.xml format errors",
    "Search engines can't read a sitemap with XML errors or an unknown root element, so the URLs in it are not discovered.",
    "Generate the sitemap with a proper XML library; it must use <urlset> or <sitemapindex> in the sitemaps.org namespace."),
  c("sitemap-too-large", "error", "Crawlability", "site", "Sitemap file too large",
    "A single sitemap may list at most 50,000 URLs and be 50 MB uncompressed. Larger files are rejected.",
    "Split the sitemap into several files referenced from a sitemap index."),
  c("sitemap-broken-urls", "error", "Crawlability", "page", "Sitemap contains broken pages",
    "The sitemap lists URLs that return 4XX/5XX. Sitemaps should only contain live, indexable pages.",
    "Remove the broken URLs from the sitemap (or restore the pages) and regenerate it automatically on publish."),
  c("very-slow-page", "error", "Performance", "page", "Very slow page load (over 3 s)",
    "The HTML took more than 3 seconds to download. Slow server responses delay every other metric and frustrate users.",
    "Profile the server response: add caching (page/CDN), optimize database queries and reduce server-side work."),

  /* ------------------------------------------------ Warnings ------------------------------------------------ */
  c("redirect-chain", "warning", "Crawlability", "page", "Redirect chains",
    "The URL passes through two or more redirects before reaching the final page. Each hop adds latency and may lose ranking signals.",
    "Redirect the first URL straight to the final destination and update internal links to the final URL."),
  c("bot-challenge", "warning", "Crawlability", "page", "Pages served a bot-protection challenge",
    "Instead of the page, the server answered with a bot-protection interstitial (CAPTCHA, proof-of-work or “checking your browser”). Search engine crawlers that get the same treatment can't see or index the content.",
    "Allowlist verified search engine bots (and SynapseSEOBot for audits) in your CDN/WAF bot protection, or relax the challenge rules for normal page requests."),
  c("crawl-throttled", "warning", "Crawlability", "site", "Crawler was rate-limited or blocked",
    "The site started rate-limiting (HTTP 429/503), challenging or timing out during the crawl, so the audit stopped early to avoid overloading it. Aggressive limits can also slow down search engine crawling.",
    "Allow SynapseSEOBot in your firewall/bot protection, or raise the crawl delay in Site Audit settings, then re-run the audit. Check your server capacity and rate-limit rules for legitimate crawlers."),
  c("temporary-redirect", "warning", "Crawlability", "page", "Temporary redirects",
    "302/303/307 redirects tell search engines the move is temporary, so they keep the old URL indexed.",
    "Use 301/308 for permanent moves; keep 302/307 only for genuinely temporary situations."),
  c("meta-refresh", "warning", "Crawlability", "page", "Pages with a meta refresh tag",
    "Meta refresh redirects are slow, poorly supported for passing signals and confusing for users.",
    "Replace meta refresh with a server-side 301 redirect."),
  c("canonical-redirect", "warning", "Crawlability", "page", "Canonical URL points to a redirect",
    "The canonical target redirects elsewhere, sending mixed signals about the preferred URL.",
    "Set the canonical to the final URL of the redirect."),
  c("canonical-chain", "warning", "Crawlability", "page", "Canonical points to a non-canonical page",
    "The canonical target itself declares a different canonical URL, forming a chain that search engines may not follow.",
    "Point every canonical directly at the ultimate preferred URL."),
  c("sitemap-missing", "warning", "Crawlability", "site", "sitemap.xml not found",
    "No sitemap was found in robots.txt or at /sitemap.xml. Sitemaps help search engines discover and prioritize pages.",
    "Publish an XML sitemap of all indexable pages and reference it in robots.txt (Sitemap: https://…/sitemap.xml)."),
  c("sitemap-not-in-robots", "warning", "Crawlability", "site", "Sitemap not referenced in robots.txt",
    "robots.txt is the first place crawlers look for sitemaps; without a Sitemap: line they must be told about it separately.",
    "Add “Sitemap: <absolute sitemap URL>” to robots.txt."),
  c("sitemap-redirects", "warning", "Crawlability", "page", "Sitemap contains redirected URLs",
    "Sitemaps should list final URLs. Redirecting entries waste crawl budget.",
    "Replace each redirected URL in the sitemap with its final destination."),
  c("sitemap-noindex", "warning", "Crawlability", "page", "Sitemap contains noindex or non-canonical URLs",
    "Listing pages you don't want indexed (noindex, or canonicalized elsewhere) sends contradictory signals.",
    "Only include canonical, indexable URLs in the sitemap."),
  c("sitemap-foreign", "warning", "Crawlability", "site", "Sitemap lists URLs from other domains",
    "A sitemap may only contain URLs from the host it is served on (unless cross-submitted), so foreign URLs are ignored.",
    "Remove URLs from other domains or host the sitemap on the right domain."),
  c("blocked-resources", "warning", "Crawlability", "link", "Internal resources blocked by robots.txt",
    "CSS/JS/images blocked by robots.txt prevent search engines from rendering the page as users see it.",
    "Allow crawling of the asset paths needed to render pages (remove the matching Disallow rules)."),
  c("missing-description", "warning", "Content", "page", "Missing meta description",
    "Without a description, search engines pick a random text snippet, which usually converts worse.",
    "Write a compelling 70–160 character meta description for each important page."),
  c("title-too-short", "warning", "Content", "page", "Title too short",
    "Very short titles (under 30 characters) waste valuable search-result space and rarely describe the page well.",
    "Expand the title with the main topic and a differentiator, aiming for 30–60 characters."),
  c("missing-h1", "warning", "Content", "page", "Missing H1 heading",
    "The H1 tells users and search engines what the page is about.",
    "Add a single, descriptive H1 near the top of the main content."),
  c("title-equals-h1", "warning", "Content", "page", "Identical title and H1",
    "Using exactly the same text for title and H1 misses a chance to target variations of the topic.",
    "Keep them consistent in meaning but vary the wording."),
  c("low-word-count", "warning", "Content", "page", "Low word count",
    "Pages with fewer than 200 words often lack the depth to satisfy search intent (thin content).",
    "Expand the page with useful, original content, or merge it into a stronger page. Ignore for pages that are thin by design (e.g. contact)."),
  c("low-text-ratio", "warning", "Content", "page", "Low text to HTML ratio",
    "Visible text is under 10% of the HTML, often a sign of bloated markup, inline scripts or thin content.",
    "Remove unnecessary inline code and markup, move scripts/styles to external files and add meaningful text."),
  c("missing-alt", "warning", "Content", "page", "Images without alt attributes",
    "Alt text describes images for screen readers and image search. Missing alt attributes hurt accessibility and image SEO.",
    "Add a concise alt description to informative images; use alt=\"\" for purely decorative ones."),
  c("nofollow-internal", "warning", "Internal linking", "page", "Nofollow attributes on internal links",
    "rel=nofollow on internal links stops link equity from flowing to your own pages.",
    "Remove nofollow from internal links. Use noindex or robots.txt to control indexing instead."),
  c("too-many-links", "warning", "Internal linking", "page", "Too many on-page links",
    "Pages with more than 300 links dilute the value passed through each link and can overwhelm visitors.",
    "Trim navigation and footer links, paginate long lists and keep only the most useful links."),
  c("slow-page", "warning", "Performance", "page", "Slow page load (1–3 s)",
    "The HTML took over 1 second to download, which delays rendering and hurts Core Web Vitals.",
    "Enable server/CDN caching, compress responses and reduce server processing time."),
  c("html-large", "warning", "Performance", "page", "HTML size too large",
    "The HTML document is larger than 2 MB. Search engines may truncate it and it slows down every visit.",
    "Remove inline data blobs, large inline SVG/CSS/JS and unnecessary markup; paginate very long pages."),
  c("uncompressed", "warning", "Performance", "page", "Uncompressed pages",
    "The server returned HTML without gzip or Brotli compression, wasting bandwidth and time.",
    "Enable gzip or Brotli compression for text responses on the server or CDN."),
  c("http-link-on-https", "warning", "HTTPS", "page", "Links on HTTPS pages lead to HTTP pages",
    "Internal links to http:// URLs force an extra redirect and may expose users to insecure pages.",
    "Update internal links to use https:// URLs."),
  c("mixed-content", "warning", "HTTPS", "page", "Mixed content",
    "The HTTPS page loads resources over plain HTTP. Browsers block or warn about such content.",
    "Load every image, script, stylesheet and iframe over HTTPS."),
  c("http-pages", "warning", "HTTPS", "page", "Non-secure pages (HTTP)",
    "These pages are served over HTTP, so browsers label them “Not secure”.",
    "Serve the pages over HTTPS and 301-redirect the HTTP URLs."),
  c("canonical-http", "warning", "HTTPS", "page", "HTTPS page canonicalizes to HTTP",
    "Pointing canonicals at the insecure version asks search engines to index HTTP URLs.",
    "Point canonicals at the https:// version."),
  c("missing-lang", "warning", "International SEO", "page", "Missing language (lang) attribute",
    "<html lang> declares the page language for browsers, screen readers and translation tools.",
    "Add lang with the page language, e.g. <html lang=\"en\">."),
  c("lang-invalid", "warning", "International SEO", "page", "Invalid lang attribute value",
    "The lang attribute is not a valid BCP 47 language tag, so browsers and assistive tech can't use it.",
    "Use a valid tag such as en, en-US or pt-BR."),
  c("hreflang-lang-mismatch", "warning", "International SEO", "page", "hreflang and lang attribute mismatch",
    "The page's self-referencing hreflang language differs from its <html lang>, suggesting wrong annotations.",
    "Make the self-referencing hreflang code match the actual page language."),
  c("hreflang-no-self", "warning", "International SEO", "page", "hreflang set without self-reference",
    "Each page in an hreflang cluster should list itself as an alternate too.",
    "Add a self-referencing hreflang entry with the page's own language code."),
  c("hreflang-relative", "warning", "International SEO", "page", "hreflang URLs are not absolute",
    "hreflang alternate URLs must be fully qualified (including https://).",
    "Use absolute URLs in every hreflang annotation."),
  c("viewport-missing", "warning", "Markup", "page", "Missing viewport meta tag",
    "Without <meta name=\"viewport\">, mobile browsers render a zoomed-out desktop layout; Google indexes mobile-first.",
    "Add <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> and make the layout responsive."),
  c("missing-doctype", "warning", "Markup", "page", "Doctype not declared",
    "Without <!DOCTYPE html> browsers render in quirks mode, which can break layout.",
    "Start every HTML document with <!DOCTYPE html>."),
  c("missing-charset", "warning", "Markup", "page", "Character encoding not declared",
    "Without a charset (header or <meta charset>), browsers may display garbled characters.",
    "Send Content-Type: text/html; charset=utf-8 and add <meta charset=\"utf-8\"> as the first element in <head>."),
  c("cwv-lcp", "warning", "Core Web Vitals", "page", "Slow Largest Contentful Paint (LCP > 2.5 s)",
    "LCP measures when the main content becomes visible. Above 2.5 s the page feels slow and fails Core Web Vitals.",
    "Optimize the LCP element: serve a properly sized, preloaded hero image (AVIF/WebP), reduce server response time and remove render-blocking CSS/JS."),
  c("cwv-cls", "warning", "Core Web Vitals", "page", "High Cumulative Layout Shift (CLS > 0.1)",
    "Elements that move while the page loads cause misclicks and frustration.",
    "Reserve space for images, embeds and ads with width/height or aspect-ratio, and avoid inserting content above existing content."),
  c("cwv-inp", "warning", "Core Web Vitals", "page", "Slow Interaction to Next Paint (INP > 200 ms)",
    "INP (real-user field data) measures responsiveness to clicks and taps. Above 200 ms the page feels laggy.",
    "Break up long JavaScript tasks, defer non-critical scripts, and reduce the work done in event handlers."),
  c("psi-low-score", "warning", "Core Web Vitals", "page", "Low PageSpeed performance score (< 50)",
    "Lighthouse rates the page's lab performance as poor.",
    "Open the page in PageSpeed Insights and work through the top opportunities (images, render-blocking resources, unused JS)."),

  /* ------------------------------------------------ Notices ------------------------------------------------ */
  c("permanent-redirect", "notice", "Crawlability", "page", "Permanent redirects",
    "301/308 redirects are fine, but internal links and sitemaps should point to final URLs to avoid extra hops.",
    "Update internal links that point at these URLs to their destination."),
  c("links-to-redirects", "notice", "Internal linking", "link", "Internal links pointing to redirects",
    "Linking to URLs that redirect adds a hop for every visitor and crawler.",
    "Change the links to point at the final URL directly."),
  c("noindex", "notice", "Crawlability", "page", "Pages blocked by noindex",
    "These pages ask search engines not to index them (meta robots or X-Robots-Tag). Make sure that's intentional.",
    "Remove noindex from pages that should rank; keep it on thin/utility pages."),
  c("robots-blocked", "notice", "Crawlability", "page", "Pages blocked by robots.txt",
    "robots.txt prevents crawling these URLs, so their content can't be evaluated (they may still be indexed from links).",
    "Review the Disallow rules; allow pages that should rank. Use noindex (not robots.txt) to keep pages out of the index."),
  c("nofollow-page", "notice", "Crawlability", "page", "Pages with a nofollow robots directive",
    "A page-level nofollow tells search engines not to follow any link on the page.",
    "Remove the nofollow directive unless you deliberately want to stop link discovery from these pages."),
  c("robots-missing", "notice", "Crawlability", "site", "robots.txt not found",
    "Without robots.txt everything may be crawled, and you can't point crawlers to your sitemap there.",
    "Add a /robots.txt with any rules you need and a Sitemap: line."),
  c("llms-missing", "notice", "Crawlability", "site", "llms.txt not found",
    "llms.txt is an emerging convention that gives AI assistants a curated, markdown summary of your site.",
    "Publish /llms.txt with an H1 site name, a short summary and links to your key pages."),
  c("llms-format", "notice", "Crawlability", "site", "llms.txt formatting issues",
    "The llms.txt file exists but doesn't follow the expected markdown structure (H1 title, summary, link lists).",
    "Start the file with “# Site name”, add a “> summary” line and markdown link lists."),
  c("missing-canonical", "notice", "Crawlability", "page", "No canonical tag",
    "Declaring a self-referencing canonical protects against duplicates created by tracking parameters and alternate hosts.",
    "Add <link rel=\"canonical\" href=\"<absolute URL of this page>\">."),
  c("non-canonical", "notice", "Crawlability", "page", "Canonicalized pages",
    "These pages point their canonical at a different URL, so they won't be indexed themselves. Check that's intentional.",
    "Only canonicalize true duplicates; important pages should be self-canonical."),
  c("underscores-url", "notice", "Crawlability", "page", "Underscores in URL",
    "Search engines treat hyphens as word separators but not underscores.",
    "Prefer hyphens in new URLs; don't change existing URLs without 301 redirects."),
  c("url-too-long", "notice", "Crawlability", "page", "URL longer than 200 characters",
    "Very long URLs are hard to share and may be truncated.",
    "Use short, descriptive paths."),
  c("too-many-params", "notice", "Crawlability", "page", "URLs with more than 2 query parameters",
    "Many parameters create near-infinite URL variations that waste crawl budget.",
    "Limit parameter URLs, canonicalize them to the clean version and avoid linking to parameter combinations."),
  c("orphan-sitemap", "notice", "Internal linking", "page", "Orphaned sitemap pages",
    "These sitemap URLs were crawled but no crawled page links to them. Pages without internal links get little link equity.",
    "Link to them from relevant pages or navigation, or remove them from the sitemap if obsolete."),
  c("deep-pages", "notice", "Internal linking", "page", "Page crawl depth more than 3 clicks",
    "Pages more than 3 clicks from the homepage are crawled less often and considered less important.",
    "Flatten the architecture: link important deep pages from hubs, categories or the homepage."),
  c("single-inlink", "notice", "Internal linking", "page", "Pages with only one incoming internal link",
    "A single internal link gives the page little link equity and discoverability.",
    "Add contextual links from related pages."),
  c("no-outlinks", "notice", "Internal linking", "page", "Pages without outgoing internal links",
    "Dead-end pages stop visitors and crawlers from continuing through the site.",
    "Add navigation or contextual links to related pages."),
  c("nofollow-external", "notice", "Internal linking", "page", "Nofollow attributes on external links",
    "rel=nofollow on outgoing links is fine for paid or untrusted links; check it's not applied everywhere by default.",
    "Use rel=sponsored or ugc where appropriate and let editorial links pass value."),
  c("empty-anchor", "notice", "Internal linking", "page", "Links with no anchor text",
    "Links without text (or an image alt) give no context to users, screen readers or search engines.",
    "Add descriptive anchor text, or alt text on linked images, or an aria-label."),
  c("title-too-long", "notice", "Content", "page", "Title too long",
    "Titles over 70 characters are usually truncated in search results.",
    "Keep titles under about 60–70 characters with the key topic first."),
  c("description-too-long", "notice", "Content", "page", "Meta description too long",
    "Descriptions over 160 characters get truncated in results.",
    "Keep the key message within the first 150–160 characters."),
  c("description-too-short", "notice", "Content", "page", "Meta description too short",
    "Descriptions under 70 characters rarely explain the page's value.",
    "Expand to 70–160 characters with a clear benefit or call to action."),
  c("multiple-h1", "notice", "Content", "page", "Multiple H1 headings",
    "Several H1s can blur the main topic of the page.",
    "Use one H1 for the main heading and H2–H6 for sections."),
  c("no-hsts", "notice", "HTTPS", "site", "No HSTS support",
    "Strict-Transport-Security makes browsers always use HTTPS, preventing downgrade attacks and saving a redirect.",
    "Send Strict-Transport-Security: max-age=31536000; includeSubDomains on HTTPS responses."),
  c("missing-security-headers", "notice", "HTTPS", "site", "Missing security headers",
    "X-Content-Type-Options and Content-Security-Policy protect visitors against MIME sniffing and content injection.",
    "Add X-Content-Type-Options: nosniff and a Content-Security-Policy suited to your site."),
  c("hreflang-no-xdefault", "notice", "International SEO", "page", "hreflang without x-default",
    "x-default tells search engines which version to show users whose language doesn't match any alternate.",
    "Add an hreflang=\"x-default\" entry pointing to your language selector or default version."),
  c("no-structured-data", "notice", "Markup", "page", "Pages without structured data",
    "Structured data (schema.org) makes pages eligible for rich results and helps machines understand them.",
    "Add JSON-LD appropriate to the page type (Organization, Article, Product, BreadcrumbList…)."),
  c("missing-og", "notice", "Markup", "page", "Missing Open Graph tags",
    "Open Graph tags control how pages look when shared on social networks and messaging apps.",
    "Add og:title, og:description, og:image and og:url."),
  c("missing-twitter", "notice", "Markup", "page", "Missing Twitter Card tags",
    "Without twitter:card, links shared on X fall back to a plain preview.",
    "Add twitter:card (summary_large_image) plus title/description/image or rely on matching OG tags."),
  c("frames", "notice", "Markup", "page", "Pages use frames",
    "<frame>/<frameset> content is hard for search engines to attribute to the page.",
    "Replace frames with regular HTML content."),
  c("flash", "notice", "Markup", "page", "Pages use Flash",
    "Flash is no longer supported by browsers; its content is invisible.",
    "Replace Flash with HTML5 content."),
  c("too-many-resources", "notice", "Performance", "page", "Too many JavaScript and CSS files",
    "More than 30 script and stylesheet files means many requests before the page is usable.",
    "Bundle and code-split assets, drop unused libraries and defer non-critical scripts."),
  c("cwv-tbt", "notice", "Core Web Vitals", "page", "Long Total Blocking Time (TBT > 200 ms)",
    "TBT (lab) measures how long the main thread is blocked during load, a proxy for poor responsiveness.",
    "Reduce and split JavaScript, remove unused code and defer third-party scripts."),
];

export const CHECK_MAP: Record<string, CheckDef> = Object.fromEntries(CHECKS.map((x) => [x.id, x]));
export const SEVERITY_ORDER: Record<Severity, number> = { error: 0, warning: 1, notice: 2 };
export const SEVERITY_LABEL: Record<Severity, string> = { error: "Errors", warning: "Warnings", notice: "Notices" };

export const THEMES: { key: ThemeKey; label: string; category: Category; description: string }[] = [
  { key: "crawlability", label: "Crawlability", category: "Crawlability", description: "Status codes, redirects, robots.txt, sitemaps and canonicals" },
  { key: "https", label: "HTTPS", category: "HTTPS", description: "Certificate, redirects, mixed content and security headers" },
  { key: "international", label: "International SEO", category: "International SEO", description: "hreflang annotations and language attributes" },
  { key: "cwv", label: "Core Web Vitals", category: "Core Web Vitals", description: "LCP, INP, CLS and TBT from PageSpeed Insights" },
  { key: "performance", label: "Site Performance", category: "Performance", description: "Response time, page size, compression and assets" },
  { key: "linking", label: "Internal Linking", category: "Internal linking", description: "Broken links, depth, orphans and link attributes" },
  { key: "markup", label: "Markup", category: "Markup", description: "Structured data, Open Graph, Twitter Cards and HTML basics" },
];
export const themeOf = (category: Category) => THEMES.find((t) => t.category === category)?.key ?? null;

/** Core Web Vitals thresholds (good ≤ a, poor > b). */
export const CWV_THRESHOLDS = {
  lcp: [2500, 4000],
  inp: [200, 500],
  cls: [0.1, 0.25],
  tbt: [200, 600],
  fcp: [1800, 3000],
  si: [3400, 5800],
  ttfb: [800, 1800],
} as const;
export function cwvStatus(metric: keyof typeof CWV_THRESHOLDS, value: number | null | undefined): "good" | "ni" | "poor" | null {
  if (value == null || Number.isNaN(value)) return null;
  const [good, poor] = CWV_THRESHOLDS[metric];
  return value <= good ? "good" : value <= poor ? "ni" : "poor";
}
